name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast-scan:
    name: SAST - Bandit (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Bandit
        uses: PyCQA/bandit@main
        with:
          args: "-r . -f txt"

  terraform-scan:
    name: IaC Scan - tfsec (Terraform)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
